---
version: 2.1
orbs:
  akoi: suzuki-shunsuke/akoi@dev:pr-1
workflows:
  build:
    jobs:
      - setup
jobs:
  setup:
    docker:
      - image: alpine:3.11.6
    steps:
      - run:
          name: install git
          command: |
            apk add git curl
      - checkout
      - akoi/install
      - run:
          name: github-comment --version
          command: |
            export PATH=$PWD/bin:$PATH
            github-comment --version
