---
version: 2.1
# orbs:
#   orb: suzuki-shunsuke/akoi@0.1.0
workflows:
  build:
    jobs:
      - setup
jobs:
  setup:
    docker:
      - image: alpine:3.11.6
    steps:
      - run:
          name: install git
          command: |
            apk add git
      - checkout
      - akoi
      - run:
          name: github-comment --version
          command: |
            export PATH=$PWD/bin:$PATH
            github-comment --version

commands:
  akoi:
    description: |
      Install tools with akoi
    parameters:
      install_path:
        type: string
        default: /usr/local/bin/akoi
        description: |
          File path where akoi is installed
      version:
        type: string
        default: v2.2.1 # renovate: depName=suzuki-shunsuke/akoi
        description: |
          The version of akoi. akoi is downloaded from the release page.
      config:
        type: string
        default: ""
        description: |
          The akoi's configuration file path.
    steps:
      - run:
          name: Install akoi
          command: |
            OS=linux
            if [ "$(uname)" == Darwin ]; then
              OS=darwin
            fi
            install_dir=$(dirname "<< parameters.install_path >>")
            test -d "$install_dir" || mkdir "$install_dir"
            version=<< parameters.version >>
            curl --fail -L "https://github.com/suzuki-shunsuke/akoi/releases/download/<< parameters.version >>/akoi_${version##v}_${OS}_amd64" -o "$install_path"
            chmod a+x "$install_path"
            "$install_path" install <<# parameters.config >>-c "<< parameters.config >>"<</ parameters.config >>
